### ISSUE TITLE
... undefined reference to `SDLPango_SetColor'

### ISSUE THREAD

**Issue by 8i8** [Barakat/SDL_Pango#1]
Hi Barakat,

When I try to compile the example.c file I am receiving this error. I do not understand what is being stated in your readme file, I think that I perhaps need to change some code but am not certain as to what; I would appreciate your help. Where are the old methods, that are to be replaced with the new? I am new to SDL2 and Pango. 
 
SDL_Pango/example.c:42: undefined reference to `SDLPango_SetColor'
collect2: error: ld returned 1 exit status
Makefile:16: recipe for target 'all' failed

Thank you for your time and your code.

Iain

**Comment by Barakat** [comment]
Hi lain,

I guess you were trying to link against the original SDL_Pango? If that was the case, you don't need to. Just include the `SDL_Pango.c` file in your project and link against SDL2, freetype2 and pangoft2. So to compile `example.c` use:

    $ gcc -Wall -Wextra -pedantic -std=c99 $(pkg-config --cflags pango SDL2 freetype2 pangoft2) SDL_Pango.c example.c $(pkg-config --libs pango SDL2 freetype2 pangoft2) -o example
    $ ./example

I have updated the README file.

**Comment by 8i8** [comment]
AH great, thank you yes that has fixed it; I am still quite wet behind the ears when it comes to linking libs, starting to make sense now though.
Going to be great to have some decent anti aliasing on text in SDL thanks!

I needed to add a folder to the address of these two in SDL_Pango.c, not sure if that is just an implementation thing:

#include <freetype2/freetype/freetype.h>
#include <freetype2/freetype/ftbitmap.h>

Thank you.

**Comment by Barakat** [comment]
These two header files are part of [freetype](https://www.freetype.org/), the library that handles font rendering. [Typically included](https://www.freetype.org/freetype2/docs/tutorial/step1.html) as:

```
#include <ft2build.h>
#include FT_FREETYPE_H
#include FT_BITMAP_H
```
Esure you have freetype installed (In Ubuntu it should be`sudo apt-get install freetype2-dev`). You should see the include path of freetype using `pkg-config --cflags freetype2`.
